### ISSUE TITLE
Multilingual support for svip-o-vue

### ISSUE THREAD

**Issue by dameyerdave** [SVIPdb/svip#110]
### Problem to solve

Add multilingual support for svip-o-vue.

### Further details

The texts in the UI are all hard coded in the vue files. We should integrate i18n into svip-o-vue. 

### Proposal

Some prework has beed done by @gautier in the branch `i18n` here [https://github.com/SVIPdb/coordinator/blob/i18n/svip-o-vue/src/i18n/translate.py](https://github.com/SVIPdb/coordinator/blob/i18n/svip-o-vue/src/i18n/translate.py)
This script should atomatically find strings in vue files and add it to the locale json files. 

Please review the script and adjust it to extract all strings and add them to the locale file for english en.json or better to en.yml because i18n also supports yml what I prefer to use over json.

### Links / references

[https://kazupon.github.io/vue-i18n/](https://kazupon.github.io/vue-i18n/)

**Comment by dameyerdave** [comment]
I'm not sure if the automated way made sense. We at least need to clean it up and force to use i18n for all further modules. The most clean way to do it would be to invest a day or two to do the translation manually. It's also not that important to support YAML if it works with JSON it's ok too.

**Comment by anastasia-escher** [comment]
solved in https://github.com/SVIPdb/svip/commit/4793e52d6ba440b5687e7269e7eeb3869b60623d
