### ISSUE TITLE
GIT Cleanup

### ISSUE THREAD

**Issue by dameyerdave** [SVIPdb/svip#111]
### Summary

Cleanup git repo and adjust to new conventions

### Further details

We want to be more consistent with the latest conventions on git.

### Proposal

Rename the `master` branch to `main`
Rename the `development` branch to `develop`
Remove the `test` branch (already done) &rarr; we use develop for the test instance as well as for the api instance\
Remove stale branches (already done) &rarr; we only want to have branches that are actively developed and remove the old ones
Rename `coordinator` repository to `svip`

**Comment by anastasia-escher** [comment]
solved
